package Speckle;

import javax.swing.JOptionPane;

/**
 *
 * @author AKSHAT
 */
public class RecoveryKey extends javax.swing.JFrame {

    /**
     * Creates new form RecoveryKey
     */
    public RecoveryKey() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Left_Border = new javax.swing.JPanel();
        Top_Border = new javax.swing.JPanel();
        Right_Border = new javax.swing.JPanel();
        Bottom_Border = new javax.swing.JPanel();
        Reset_Recovery_Label = new javax.swing.JLabel();
        Password_Label = new javax.swing.JLabel();
        Password = new javax.swing.JPasswordField();
        Cancel_Label = new javax.swing.JLabel();
        Reset_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(392, 152));

        Left_Border.setBackground(new java.awt.Color(60, 60, 60));
        Left_Border.setPreferredSize(new java.awt.Dimension(2, 151));

        javax.swing.GroupLayout Left_BorderLayout = new javax.swing.GroupLayout(Left_Border);
        Left_Border.setLayout(Left_BorderLayout);
        Left_BorderLayout.setHorizontalGroup(
            Left_BorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );
        Left_BorderLayout.setVerticalGroup(
            Left_BorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 151, Short.MAX_VALUE)
        );

        Top_Border.setBackground(new java.awt.Color(60, 60, 60));
        Top_Border.setPreferredSize(new java.awt.Dimension(400, 2));

        javax.swing.GroupLayout Top_BorderLayout = new javax.swing.GroupLayout(Top_Border);
        Top_Border.setLayout(Top_BorderLayout);
        Top_BorderLayout.setHorizontalGroup(
            Top_BorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        Top_BorderLayout.setVerticalGroup(
            Top_BorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        Right_Border.setBackground(new java.awt.Color(60, 60, 60));

        javax.swing.GroupLayout Right_BorderLayout = new javax.swing.GroupLayout(Right_Border);
        Right_Border.setLayout(Right_BorderLayout);
        Right_BorderLayout.setHorizontalGroup(
            Right_BorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );
        Right_BorderLayout.setVerticalGroup(
            Right_BorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 151, Short.MAX_VALUE)
        );

        Bottom_Border.setBackground(new java.awt.Color(60, 60, 60));
        Bottom_Border.setPreferredSize(new java.awt.Dimension(400, 2));

        javax.swing.GroupLayout Bottom_BorderLayout = new javax.swing.GroupLayout(Bottom_Border);
        Bottom_Border.setLayout(Bottom_BorderLayout);
        Bottom_BorderLayout.setHorizontalGroup(
            Bottom_BorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        Bottom_BorderLayout.setVerticalGroup(
            Bottom_BorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        Reset_Recovery_Label.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        Reset_Recovery_Label.setText("Reset Recovery Key");

        Password_Label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Password_Label.setText("PASSWORD");

        Password.setPreferredSize(new java.awt.Dimension(10, 20));

        Cancel_Label.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        Cancel_Label.setText("Cancel");
        Cancel_Label.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Cancel_LabelMouseMoved(evt);
            }
        });
        Cancel_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Cancel_LabelMousePressed(evt);
            }
        });

        Reset_Button.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        Reset_Button.setText("Reset");
        Reset_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Reset_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(170, 170, 170)
                                .addComponent(Cancel_Label))
                            .addComponent(Left_Border, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Reset_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))
                    .addComponent(Bottom_Border, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Top_Border, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Reset_Recovery_Label)
                            .addComponent(Password_Label)
                            .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addComponent(Right_Border, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(Bottom_Border, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cancel_Label)
                    .addComponent(Reset_Button)))
            .addComponent(Left_Border, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(Right_Border, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(Reset_Recovery_Label))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(Password_Label))
                    .addComponent(Top_Border, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setSize(new java.awt.Dimension(352, 152));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Cancel_LabelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Cancel_LabelMouseMoved
        Cancel_Label.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_Cancel_LabelMouseMoved

    private void Cancel_LabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Cancel_LabelMousePressed
        this.setVisible(false);
    }//GEN-LAST:event_Cancel_LabelMousePressed

    private void Reset_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Reset_ButtonActionPerformed
        String passwd = new String(Password.getPassword());
        String key = Internal.Function.randomAlphaNumeric(16);
        if (!Internal.Security.validateHash(passwd, Internal.SQLite.getConfigValue("Password")))
            JOptionPane.showMessageDialog(null, "The Password You Have Entered is Incorrect."
                + " Please Try Again!", "Incorrect Password", JOptionPane.ERROR_MESSAGE);
        else {
            Internal.SQLite.setConfigValue("Recovery Key", Internal.Security.generateHash(key));
            this.setVisible(false);
            JOptionPane.showMessageDialog(null, "Recovery Key Has Been Reset Successfully!",
                "Success", JOptionPane.INFORMATION_MESSAGE);
            JOptionPane.showMessageDialog(null, "Your New Recovery Key is " + key,
                "Recovery Key", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_Reset_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If FlatIntelliJLaf is not available, stay with the default look and feel. */
        com.formdev.flatlaf.FlatIntelliJLaf.setup();
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("FlatIntelliJLaf".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        javax.swing.UIManager.put("ScrollBar.thumbArc", 999);
        javax.swing.UIManager.put("ScrollBar.thumbInsets", new java.awt.Insets(2, 2, 2, 2));
        javax.swing.UIManager.put("TabbedPane.showTabSeparators", true);
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new RecoveryKey().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Bottom_Border;
    private javax.swing.JLabel Cancel_Label;
    private javax.swing.JPanel Left_Border;
    private javax.swing.JPasswordField Password;
    private javax.swing.JLabel Password_Label;
    private javax.swing.JButton Reset_Button;
    private javax.swing.JLabel Reset_Recovery_Label;
    private javax.swing.JPanel Right_Border;
    private javax.swing.JPanel Top_Border;
    // End of variables declaration//GEN-END:variables
}
