package Speckle;

import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author Astralsphere Arts
 */
public class Home extends javax.swing.JPanel {

    /**
     * Creates new form Home
     */
    public Home() {
        this.data = Internal.SQLite.dashData();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Banner = new javax.swing.JPanel();
        Speckle_Label = new javax.swing.JLabel();
        Speckle_Version_Label = new javax.swing.JLabel();
        Help = new javax.swing.JPanel();
        Help_Container = new javax.swing.JScrollPane();
        Help_Text = new javax.swing.JTextArea();
        Low_Stock = new javax.swing.JPanel();
        Low_Stock_Label = new javax.swing.JLabel();
        Low_Stock_Para = new javax.swing.JLabel();
        Product_One_Label = new javax.swing.JLabel();
        Product_One_Quantity = new javax.swing.JLabel();
        Product_Two_Label = new javax.swing.JLabel();
        Product_Two_Quantity = new javax.swing.JLabel();
        Product_Three_Label = new javax.swing.JLabel();
        Product_Three_Quantity = new javax.swing.JLabel();
        Product_Four_Label = new javax.swing.JLabel();
        Product_Four_Quantity = new javax.swing.JLabel();
        Product_Five_Label = new javax.swing.JLabel();
        Product_Five_Quantity = new javax.swing.JLabel();

        Banner.setBackground(new java.awt.Color(253, 253, 253));
        Banner.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(180, 180, 180), 1, true));

        Speckle_Label.setFont(new java.awt.Font("Segoe UI Semibold", 0, 30)); // NOI18N
        Speckle_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Speckle_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/speckle-home-logo.png"))); // NOI18N
        Speckle_Label.setText("Speckle");

        Speckle_Version_Label.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        Speckle_Version_Label.setText("0.7-beta");

        javax.swing.GroupLayout BannerLayout = new javax.swing.GroupLayout(Banner);
        Banner.setLayout(BannerLayout);
        BannerLayout.setHorizontalGroup(
            BannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BannerLayout.createSequentialGroup()
                .addContainerGap(317, Short.MAX_VALUE)
                .addComponent(Speckle_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Speckle_Version_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(288, 288, 288))
        );
        BannerLayout.setVerticalGroup(
            BannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BannerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Speckle_Label, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                    .addComponent(Speckle_Version_Label))
                .addContainerGap())
        );

        Help.setBackground(new java.awt.Color(248, 248, 248));
        Help.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(180, 180, 180), 1, true));

        Help_Container.setBorder(null);

        Help_Text.setEditable(false);
        Help_Text.setBackground(new java.awt.Color(248, 248, 248));
        Help_Text.setColumns(20);
        Help_Text.setRows(5);
        Help_Text.setBorder(null);
        Help_Caret = (javax.swing.text.DefaultCaret)Help_Text.getCaret();
        Help_Caret.setUpdatePolicy(javax.swing.text.DefaultCaret.NEVER_UPDATE);
        try {
            Help_Reader = new java.io.BufferedReader(new java.io.InputStreamReader(getClass().getResourceAsStream("/Resources/help.txt")));
            Help_Line = Help_Reader.readLine();
            while (Help_Line != null) {
                Help_Text.append(Help_Line + "\n");
                Help_Line = Help_Reader.readLine();
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, ex, "Error", JOptionPane.ERROR_MESSAGE);
        }
        Help_Container.setViewportView(Help_Text);

        javax.swing.GroupLayout HelpLayout = new javax.swing.GroupLayout(Help);
        Help.setLayout(HelpLayout);
        HelpLayout.setHorizontalGroup(
            HelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Help_Container)
        );
        HelpLayout.setVerticalGroup(
            HelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Help_Container)
        );

        Low_Stock.setBackground(new java.awt.Color(248, 248, 248));
        Low_Stock.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(180, 180, 180), 1, true));

        Low_Stock_Label.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        Low_Stock_Label.setText("Low Stock");

        Low_Stock_Para.setText("<html><p>The following five Products have the least amount of Stock availabe. If you think you might run Out of Stock for a Product then please Restock.</p></html>");

        Product_One_Label.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        Product_One_Label.setText(data[0][0]);

        Product_One_Quantity.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        Product_One_Quantity.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Product_One_Quantity.setText(data[0][1]);
        Product_One_Quantity.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        Product_Two_Label.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        Product_Two_Label.setText(data[1][0]);

        Product_Two_Quantity.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        Product_Two_Quantity.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Product_Two_Quantity.setText(data[1][1]);
        Product_Two_Quantity.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        Product_Three_Label.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        Product_Three_Label.setText(data[2][0]);

        Product_Three_Quantity.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        Product_Three_Quantity.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Product_Three_Quantity.setText(data[2][1]);
        Product_Three_Quantity.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        Product_Four_Label.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        Product_Four_Label.setText(data[3][0]);

        Product_Four_Quantity.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        Product_Four_Quantity.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Product_Four_Quantity.setText(data[3][1]);
        Product_Four_Quantity.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        Product_Five_Label.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        Product_Five_Label.setText(data[4][0]);

        Product_Five_Quantity.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        Product_Five_Quantity.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Product_Five_Quantity.setText(data[4][1]);
        Product_Five_Quantity.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout Low_StockLayout = new javax.swing.GroupLayout(Low_Stock);
        Low_Stock.setLayout(Low_StockLayout);
        Low_StockLayout.setHorizontalGroup(
            Low_StockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Low_StockLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(Low_StockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(Low_StockLayout.createSequentialGroup()
                        .addComponent(Product_Five_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Product_Five_Quantity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(Low_StockLayout.createSequentialGroup()
                        .addComponent(Product_Four_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Product_Four_Quantity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(Low_StockLayout.createSequentialGroup()
                        .addComponent(Product_Three_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Product_Three_Quantity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(Low_StockLayout.createSequentialGroup()
                        .addComponent(Product_Two_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Product_Two_Quantity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(Low_Stock_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Low_StockLayout.createSequentialGroup()
                        .addComponent(Product_One_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Product_One_Quantity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(Low_Stock_Para, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        Low_StockLayout.setVerticalGroup(
            Low_StockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Low_StockLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(Low_Stock_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Low_Stock_Para, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(Low_StockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Product_One_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Product_One_Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Low_StockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Product_Two_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Product_Two_Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Low_StockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Product_Three_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Product_Three_Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Low_StockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Product_Four_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Product_Four_Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Low_StockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Product_Five_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Product_Five_Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Banner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Help, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Low_Stock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(Banner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Low_Stock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Help, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(47, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Banner;
    private javax.swing.JPanel Help;
    private javax.swing.JScrollPane Help_Container;
    private javax.swing.JTextArea Help_Text;
    private javax.swing.JPanel Low_Stock;
    private javax.swing.JLabel Low_Stock_Label;
    private javax.swing.JLabel Low_Stock_Para;
    private javax.swing.JLabel Product_Five_Label;
    private javax.swing.JLabel Product_Five_Quantity;
    private javax.swing.JLabel Product_Four_Label;
    private javax.swing.JLabel Product_Four_Quantity;
    private javax.swing.JLabel Product_One_Label;
    private javax.swing.JLabel Product_One_Quantity;
    private javax.swing.JLabel Product_Three_Label;
    private javax.swing.JLabel Product_Three_Quantity;
    private javax.swing.JLabel Product_Two_Label;
    private javax.swing.JLabel Product_Two_Quantity;
    private javax.swing.JLabel Speckle_Label;
    private javax.swing.JLabel Speckle_Version_Label;
    // End of variables declaration//GEN-END:variables
    private final String data[][];
    private javax.swing.text.DefaultCaret Help_Caret;
    private java.io.BufferedReader Help_Reader;        
    private String Help_Line;
}
