package Speckle;

import com.formdev.flatlaf.FlatIntelliJLaf;

/**
 *
 * @author Astralsphere Arts
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        SQLite.Main.initDB();
        this.Active = new java.awt.Color(0, 136, 255);
        this.Hover = new java.awt.Color(0, 165, 255);
        this.White = new java.awt.Color(255, 255, 255);
        initComponents();
        Container_Deck = (java.awt.CardLayout)Container.getLayout();
        Speckle.Home scene = new Home();
        scene.setBounds(0, 0, 955, 574);
        Content.add(scene).setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        Window_Title = new javax.swing.JLabel();
        Close = new javax.swing.JLabel();
        Container = new javax.swing.JPanel();
        StartUp = new javax.swing.JPanel();
        LogIn = new javax.swing.JButton();
        Application = new javax.swing.JPanel();
        SideBar = new javax.swing.JPanel();
        Home = new javax.swing.JLabel();
        Invoicing = new javax.swing.JLabel();
        Inventory = new javax.swing.JLabel();
        Settings = new javax.swing.JLabel();
        About = new javax.swing.JLabel();
        Content = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Speckle");
        setUndecorated(true);
        setResizable(false);

        Background.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N

        Header.setBackground(new java.awt.Color(60, 60, 60));
        Header.setForeground(new java.awt.Color(142, 142, 142));
        Header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                HeaderMouseDragged(evt);
            }
        });
        Header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HeaderMousePressed(evt);
            }
        });

        Window_Title.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        Window_Title.setForeground(new java.awt.Color(142, 142, 142));
        Window_Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Window_Title.setText("S P E C K L E");
        Window_Title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Close.setBackground(new java.awt.Color(255, 255, 255));
        Close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/close.png"))); // NOI18N
        Close.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Close.setOpaque(true);
        Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CloseMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CloseMousePressed(evt);
            }
        });

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(468, 468, 468)
                .addComponent(Window_Title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Close, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Window_Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Close, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Container.setLayout(new java.awt.CardLayout());

        LogIn.setText("Log In");
        LogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogInActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout StartUpLayout = new javax.swing.GroupLayout(StartUp);
        StartUp.setLayout(StartUpLayout);
        StartUpLayout.setHorizontalGroup(
            StartUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StartUpLayout.createSequentialGroup()
                .addGap(440, 440, 440)
                .addComponent(LogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(440, Short.MAX_VALUE))
        );
        StartUpLayout.setVerticalGroup(
            StartUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StartUpLayout.createSequentialGroup()
                .addGap(268, 268, 268)
                .addComponent(LogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(269, Short.MAX_VALUE))
        );

        Container.add(StartUp, "start");

        SideBar.setBackground(new java.awt.Color(51, 51, 51));

        Home.setBackground(new java.awt.Color(0, 136, 255));
        Home.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/home.png"))); // NOI18N
        Home.setToolTipText("Home");
        Home.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Home.setOpaque(true);
        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HomeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HomeMousePressed(evt);
            }
        });

        Invoicing.setBackground(new java.awt.Color(255, 255, 255));
        Invoicing.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Invoicing.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/invoice.png"))); // NOI18N
        Invoicing.setToolTipText("Invoicing");
        Invoicing.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Invoicing.setOpaque(true);
        Invoicing.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InvoicingMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                InvoicingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                InvoicingMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                InvoicingMousePressed(evt);
            }
        });

        Inventory.setBackground(new java.awt.Color(255, 255, 255));
        Inventory.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Inventory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/inventory.png"))); // NOI18N
        Inventory.setToolTipText("Inventory");
        Inventory.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Inventory.setOpaque(true);
        Inventory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InventoryMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                InventoryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                InventoryMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                InventoryMousePressed(evt);
            }
        });

        Settings.setBackground(new java.awt.Color(255, 255, 255));
        Settings.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Settings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/settings.png"))); // NOI18N
        Settings.setToolTipText("Settings");
        Settings.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Settings.setOpaque(true);
        Settings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SettingsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SettingsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SettingsMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SettingsMousePressed(evt);
            }
        });

        About.setBackground(new java.awt.Color(255, 255, 255));
        About.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        About.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/about.png"))); // NOI18N
        About.setToolTipText("About");
        About.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        About.setOpaque(true);
        About.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AboutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AboutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AboutMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AboutMousePressed(evt);
            }
        });

        javax.swing.GroupLayout SideBarLayout = new javax.swing.GroupLayout(SideBar);
        SideBar.setLayout(SideBarLayout);
        SideBarLayout.setHorizontalGroup(
            SideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SideBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SideBarLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Inventory))
                    .addGroup(SideBarLayout.createSequentialGroup()
                        .addGroup(SideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Invoicing)
                            .addComponent(Settings)
                            .addComponent(About)
                            .addComponent(Home))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        SideBarLayout.setVerticalGroup(
            SideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SideBarLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(Home)
                .addGap(18, 18, 18)
                .addComponent(Invoicing)
                .addGap(18, 18, 18)
                .addComponent(Inventory)
                .addGap(18, 18, 18)
                .addComponent(Settings)
                .addGap(18, 18, 18)
                .addComponent(About)
                .addContainerGap(300, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ContentLayout = new javax.swing.GroupLayout(Content);
        Content.setLayout(ContentLayout);
        ContentLayout.setHorizontalGroup(
            ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 948, Short.MAX_VALUE)
        );
        ContentLayout.setVerticalGroup(
            ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout ApplicationLayout = new javax.swing.GroupLayout(Application);
        Application.setLayout(ApplicationLayout);
        ApplicationLayout.setHorizontalGroup(
            ApplicationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ApplicationLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(SideBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Content))
        );
        ApplicationLayout.setVerticalGroup(
            ApplicationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ApplicationLayout.createSequentialGroup()
                .addGroup(ApplicationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SideBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Content))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        Container.add(Application, "app");

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void HeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_HeaderMousePressed

    private void HeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMouseDragged
        int xx = evt.getXOnScreen();
        int yy = evt.getYOnScreen();
        this.setLocation(xx - x, yy - y);
    }//GEN-LAST:event_HeaderMouseDragged

    private void CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_CloseMouseClicked

    private void CloseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMousePressed
        Close.setBackground(new java.awt.Color(225, 51, 51));
    }//GEN-LAST:event_CloseMousePressed

    private void CloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseEntered
        Close.setBackground(new java.awt.Color(225, 80, 80));
    }//GEN-LAST:event_CloseMouseEntered

    private void CloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseExited
        Close.setBackground(White);
    }//GEN-LAST:event_CloseMouseExited

    private void LogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogInActionPerformed
        Container_Deck.show(Container, "app");
    }//GEN-LAST:event_LogInActionPerformed

    private void HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseClicked
        Content.removeAll();
        Speckle.Home scene = new Home();
        scene.setBounds(0, 0, 955, 574);
        Content.add(scene).setVisible(true);
    }//GEN-LAST:event_HomeMouseClicked

    private void HomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMousePressed
        Home.setBackground(Active);
        Invoicing.setBackground(White);
        Inventory.setBackground(White);
        Settings.setBackground(White);
        About.setBackground(White);
        Stored = Home.getBackground();
    }//GEN-LAST:event_HomeMousePressed

    private void HomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseEntered
        Stored = Home.getBackground();
        Home.setBackground(Hover);
    }//GEN-LAST:event_HomeMouseEntered

    private void HomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseExited
        Home.setBackground(Stored);
    }//GEN-LAST:event_HomeMouseExited

    private void InvoicingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InvoicingMouseClicked
        Content.removeAll();
        Speckle.Invoicing scene = new Invoicing();
        scene.setBounds(0, 0, 955, 574);
        Content.add(scene).setVisible(true);
    }//GEN-LAST:event_InvoicingMouseClicked

    private void InvoicingMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InvoicingMousePressed
        Home.setBackground(White);
        Invoicing.setBackground(Active);
        Inventory.setBackground(White);
        Settings.setBackground(White);
        About.setBackground(White);
        Stored = Invoicing.getBackground();
    }//GEN-LAST:event_InvoicingMousePressed

    private void InvoicingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InvoicingMouseEntered
        Stored = Invoicing.getBackground();
        Invoicing.setBackground(Hover);
    }//GEN-LAST:event_InvoicingMouseEntered

    private void InvoicingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InvoicingMouseExited
        Invoicing.setBackground(Stored);
    }//GEN-LAST:event_InvoicingMouseExited

    private void InventoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InventoryMouseClicked
        Content.removeAll();
        Speckle.Inventory scene = new Inventory();
        scene.setBounds(0, 0, 955, 574);
        Content.add(scene).setVisible(true);
    }//GEN-LAST:event_InventoryMouseClicked

    private void InventoryMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InventoryMousePressed
        Home.setBackground(White);
        Invoicing.setBackground(White);
        Inventory.setBackground(Active);
        Settings.setBackground(White);
        About.setBackground(White);
        Stored = Inventory.getBackground();
    }//GEN-LAST:event_InventoryMousePressed

    private void InventoryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InventoryMouseEntered
        Stored = Inventory.getBackground();
        Inventory.setBackground(Hover);
    }//GEN-LAST:event_InventoryMouseEntered

    private void InventoryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InventoryMouseExited
        Inventory.setBackground(Stored);
    }//GEN-LAST:event_InventoryMouseExited

    private void SettingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SettingsMouseClicked
        Content.removeAll();
        Speckle.Settings scene = new Settings();
        scene.setBounds(0, 0, 955, 574);
        Content.add(scene).setVisible(true);
    }//GEN-LAST:event_SettingsMouseClicked

    private void SettingsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SettingsMousePressed
        Home.setBackground(White);
        Invoicing.setBackground(White);
        Inventory.setBackground(White);
        Settings.setBackground(Active);
        About.setBackground(White);
        Stored = Settings.getBackground();
    }//GEN-LAST:event_SettingsMousePressed

    private void SettingsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SettingsMouseEntered
        Stored = Settings.getBackground();
        Settings.setBackground(Hover);
    }//GEN-LAST:event_SettingsMouseEntered

    private void SettingsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SettingsMouseExited
        Settings.setBackground(Stored);
    }//GEN-LAST:event_SettingsMouseExited

    private void AboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutMouseClicked
        Content.removeAll();
        Speckle.About scene = new About();
        scene.setBounds(0, 0, 955, 574);
        Content.add(scene).setVisible(true);
    }//GEN-LAST:event_AboutMouseClicked

    private void AboutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutMousePressed
        Home.setBackground(White);
        Invoicing.setBackground(White);
        Inventory.setBackground(White);
        Settings.setBackground(White);
        About.setBackground(Active);
        Stored = About.getBackground();
    }//GEN-LAST:event_AboutMousePressed

    private void AboutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutMouseEntered
        Stored = About.getBackground();
        About.setBackground(Hover);
    }//GEN-LAST:event_AboutMouseEntered

    private void AboutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutMouseExited
        About.setBackground(Stored);
    }//GEN-LAST:event_AboutMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the FlatIntelliJLaf look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If FlatIntelliJLaf is not available, stay with the default look and feel. */
        FlatIntelliJLaf.install();
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("FlatIntelliJLaf".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Main().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel About;
    private javax.swing.JPanel Application;
    private javax.swing.JPanel Background;
    private javax.swing.JLabel Close;
    private javax.swing.JPanel Container;
    private javax.swing.JDesktopPane Content;
    private javax.swing.JPanel Header;
    private javax.swing.JLabel Home;
    private javax.swing.JLabel Inventory;
    private javax.swing.JLabel Invoicing;
    private javax.swing.JButton LogIn;
    private javax.swing.JLabel Settings;
    private javax.swing.JPanel SideBar;
    private javax.swing.JPanel StartUp;
    private javax.swing.JLabel Window_Title;
    // End of variables declaration//GEN-END:variables
    private final java.awt.CardLayout Container_Deck;
    private final java.awt.Color Active;
    private final java.awt.Color Hover;
    private final java.awt.Color White;
    private java.awt.Color Stored;
    private int x, y;
}
