package Speckle;

import javax.swing.JOptionPane;

/**
 *
 * @author Astralsphere Arts
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        Internal.SQLite.initDB();
        this.Active = new java.awt.Color(0, 136, 255);
        this.Hover = new java.awt.Color(0, 165, 255);
        this.White = new java.awt.Color(255, 255, 255);
        initComponents();
        Container_Deck = (java.awt.CardLayout)Container.getLayout();
        StartUp_Deck = (java.awt.CardLayout)StartUp_Container.getLayout();
        if (Internal.SQLite.firstUse)
            StartUp_Deck.show(StartUp_Container, "signUp1");
        else
            StartUp_Deck.show(StartUp_Container, "signIn");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        Header_Logo = new javax.swing.JLabel();
        Window_Title = new javax.swing.JLabel();
        Close = new javax.swing.JLabel();
        Container = new javax.swing.JPanel();
        StartUp = new javax.swing.JPanel();
        StartUp_Banner = new javax.swing.JLabel();
        StartUp_Container = new javax.swing.JPanel();
        SignIn = new javax.swing.JPanel();
        SignIn_Heading = new javax.swing.JLabel();
        SignIn_Para = new javax.swing.JLabel();
        SignIn_SubHeading = new javax.swing.JLabel();
        Username_Label = new javax.swing.JLabel();
        Username = new javax.swing.JTextField();
        Password_Label = new javax.swing.JLabel();
        Password = new javax.swing.JPasswordField();
        SignIn_Button = new javax.swing.JButton();
        SignUp_User = new javax.swing.JPanel();
        SignUp_User_Heading = new javax.swing.JLabel();
        SignUp_User_SubHeading = new javax.swing.JLabel();
        SignUp_User_Para_A = new javax.swing.JLabel();
        SignUp_User_Para_B = new javax.swing.JLabel();
        SignUp_Username_Label = new javax.swing.JLabel();
        SignUp_Username = new javax.swing.JTextField();
        Create_Password_Label = new javax.swing.JLabel();
        Create_Password = new javax.swing.JPasswordField();
        Confirm_Password_Label = new javax.swing.JLabel();
        Confirm_Password = new javax.swing.JPasswordField();
        Next_Button = new javax.swing.JButton();
        SignUp_Details = new javax.swing.JPanel();
        SignUp_Details_Heading = new javax.swing.JLabel();
        SignUp_Details_Para = new javax.swing.JLabel();
        Business_Name_Label = new javax.swing.JLabel();
        Business_Name = new javax.swing.JTextField();
        Contact_Number_Label = new javax.swing.JLabel();
        Contact_Number = new javax.swing.JTextField();
        Email_Address_Label = new javax.swing.JLabel();
        Email_Address = new javax.swing.JTextField();
        Business_Location_Label = new javax.swing.JLabel();
        Business_Location = new javax.swing.JTextField();
        SignUp_Button = new javax.swing.JButton();
        Application = new javax.swing.JPanel();
        SideBar = new javax.swing.JPanel();
        Home = new javax.swing.JLabel();
        Invoicing = new javax.swing.JLabel();
        Inventory = new javax.swing.JLabel();
        Settings = new javax.swing.JLabel();
        About = new javax.swing.JLabel();
        SignOut = new javax.swing.JLabel();
        Content = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Speckle");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Resources/speckle-frame-logo.png")).getImage());
        setUndecorated(true);
        setResizable(false);

        Background.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N

        Header.setBackground(new java.awt.Color(60, 60, 60));
        Header.setForeground(new java.awt.Color(142, 142, 142));
        Header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                HeaderMouseDragged(evt);
            }
        });
        Header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HeaderMousePressed(evt);
            }
        });

        Header_Logo.setBackground(new java.awt.Color(60, 60, 60));
        Header_Logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Header_Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/speckle-header-logo.png"))); // NOI18N
        Header_Logo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Header_Logo.setOpaque(true);

        Window_Title.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        Window_Title.setForeground(new java.awt.Color(142, 142, 142));
        Window_Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Window_Title.setText("S P E C K L E");
        Window_Title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Close.setBackground(new java.awt.Color(255, 255, 255));
        Close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/close.png"))); // NOI18N
        Close.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Close.setOpaque(true);
        Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CloseMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CloseMousePressed(evt);
            }
        });

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addComponent(Header_Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(442, 442, 442)
                .addComponent(Window_Title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Close, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Window_Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Close, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(HeaderLayout.createSequentialGroup()
                .addComponent(Header_Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        Container.setLayout(new java.awt.CardLayout());

        StartUp_Banner.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        StartUp_Banner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/banner.png"))); // NOI18N
        StartUp_Banner.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        StartUp_Container.setLayout(new java.awt.CardLayout());

        SignIn_Heading.setFont(new java.awt.Font("Segoe UI Semibold", 0, 30)); // NOI18N
        SignIn_Heading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SignIn_Heading.setText("Welcome To Speckle!");
        SignIn_Heading.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        SignIn_Para.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        SignIn_Para.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SignIn_Para.setText("A Simple Invoicing and Inventory Management System");
        SignIn_Para.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        SignIn_SubHeading.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        SignIn_SubHeading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SignIn_SubHeading.setText("Please Sign In");
        SignIn_SubHeading.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Username_Label.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        Username_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Username_Label.setText("Username");
        Username_Label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Username.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        Password_Label.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        Password_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Password_Label.setText("Password");
        Password_Label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Password.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        SignIn_Button.setText("Sign In");
        SignIn_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignIn_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SignInLayout = new javax.swing.GroupLayout(SignIn);
        SignIn.setLayout(SignInLayout);
        SignInLayout.setHorizontalGroup(
            SignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SignInLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(SignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(SignIn_SubHeading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SignIn_Heading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SignIn_Para, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SignInLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(SignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Username_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Password_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(SignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Username)
                            .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SignIn_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        SignInLayout.setVerticalGroup(
            SignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SignInLayout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(SignIn_Heading, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SignIn_Para)
                .addGap(55, 55, 55)
                .addComponent(SignIn_SubHeading)
                .addGap(18, 18, 18)
                .addGroup(SignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Username_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Password_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(SignIn_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(136, Short.MAX_VALUE))
        );

        StartUp_Container.add(SignIn, "signIn");

        SignUp_User_Heading.setFont(new java.awt.Font("Segoe UI Semibold", 0, 30)); // NOI18N
        SignUp_User_Heading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SignUp_User_Heading.setText("Welcome To Speckle!");
        SignUp_User_Heading.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        SignUp_User_SubHeading.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        SignUp_User_SubHeading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SignUp_User_SubHeading.setText("A Simple Invoicing and Inventory Management System");
        SignUp_User_SubHeading.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        SignUp_User_Para_A.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SignUp_User_Para_A.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SignUp_User_Para_A.setText("<html><p style=\"text-align: center;\">Since this is your first time using Speckle, we need some details<br>to set things up for you.</p></html>");
        SignUp_User_Para_A.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        SignUp_User_Para_B.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SignUp_User_Para_B.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SignUp_User_Para_B.setText("<html><p style=\"text-align: center;\">First, create a Username and Password for yourself that you'll be<br>using every time you use Speckle.</p></html>");
        SignUp_User_Para_B.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        SignUp_Username_Label.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        SignUp_Username_Label.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SignUp_Username_Label.setText("Your Username");
        SignUp_Username_Label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        SignUp_Username.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        Create_Password_Label.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        Create_Password_Label.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Create_Password_Label.setText("Create Password");
        Create_Password_Label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Create_Password.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        Confirm_Password_Label.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        Confirm_Password_Label.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Confirm_Password_Label.setText("Confirm Password");
        Confirm_Password_Label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Confirm_Password.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        Next_Button.setText("Next");
        Next_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Next_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SignUp_UserLayout = new javax.swing.GroupLayout(SignUp_User);
        SignUp_User.setLayout(SignUp_UserLayout);
        SignUp_UserLayout.setHorizontalGroup(
            SignUp_UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SignUp_UserLayout.createSequentialGroup()
                .addGap(0, 31, Short.MAX_VALUE)
                .addGroup(SignUp_UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SignUp_User_Para_A, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(SignUp_UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(SignUp_User_Para_B)
                        .addComponent(SignUp_User_Heading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SignUp_User_SubHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SignUp_UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, SignUp_UserLayout.createSequentialGroup()
                            .addGap(160, 160, 160)
                            .addComponent(Next_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, SignUp_UserLayout.createSequentialGroup()
                            .addGap(38, 38, 38)
                            .addGroup(SignUp_UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(SignUp_UserLayout.createSequentialGroup()
                                    .addGroup(SignUp_UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(Create_Password_Label, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                        .addComponent(Confirm_Password_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(SignUp_UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Confirm_Password)
                                        .addComponent(Create_Password)))
                                .addGroup(SignUp_UserLayout.createSequentialGroup()
                                    .addComponent(SignUp_Username_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(SignUp_Username, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE))))
                .addGap(31, 31, 31))
        );
        SignUp_UserLayout.setVerticalGroup(
            SignUp_UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SignUp_UserLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(SignUp_User_Heading, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SignUp_User_SubHeading)
                .addGap(50, 50, 50)
                .addComponent(SignUp_User_Para_A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SignUp_User_Para_B, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(SignUp_UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SignUp_Username_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SignUp_Username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SignUp_UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Create_Password_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Create_Password))
                .addGap(11, 11, 11)
                .addGroup(SignUp_UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Confirm_Password_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Confirm_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(Next_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        StartUp_Container.add(SignUp_User, "signUp1");

        SignUp_Details_Heading.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        SignUp_Details_Heading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SignUp_Details_Heading.setText("Just a little more and you'll be all ready to go.");
        SignUp_Details_Heading.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        SignUp_Details_Para.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SignUp_Details_Para.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SignUp_Details_Para.setText("<html><p style=\"text-align: center;\">Now, please provide some details about your Business.<br> This information will be used for the Invoices you generate using<br>Speckle.</p></html>");
        SignUp_Details_Para.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Business_Name_Label.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        Business_Name_Label.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Business_Name_Label.setText("Business Name");
        Business_Name_Label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Business_Name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        Contact_Number_Label.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        Contact_Number_Label.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Contact_Number_Label.setText("Contact Number");
        Contact_Number_Label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Contact_Number.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        Email_Address_Label.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        Email_Address_Label.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Email_Address_Label.setText("Email Address");
        Email_Address_Label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Email_Address.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        Business_Location_Label.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        Business_Location_Label.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Business_Location_Label.setText("<html><p>Business Location<br>(Address)</p></html>");
        Business_Location_Label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Business_Location.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        SignUp_Button.setText("Sign Up");
        SignUp_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUp_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SignUp_DetailsLayout = new javax.swing.GroupLayout(SignUp_Details);
        SignUp_Details.setLayout(SignUp_DetailsLayout);
        SignUp_DetailsLayout.setHorizontalGroup(
            SignUp_DetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SignUp_DetailsLayout.createSequentialGroup()
                .addGroup(SignUp_DetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SignUp_DetailsLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(SignUp_DetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SignUp_Details_Heading, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
                            .addComponent(SignUp_Details_Para)))
                    .addGroup(SignUp_DetailsLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(SignUp_DetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(SignUp_DetailsLayout.createSequentialGroup()
                                .addComponent(Business_Location_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Business_Location))
                            .addGroup(SignUp_DetailsLayout.createSequentialGroup()
                                .addComponent(Email_Address_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Email_Address, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(SignUp_DetailsLayout.createSequentialGroup()
                                .addComponent(Business_Name_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Business_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(SignUp_DetailsLayout.createSequentialGroup()
                                .addComponent(Contact_Number_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Contact_Number, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(SignUp_DetailsLayout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(SignUp_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        SignUp_DetailsLayout.setVerticalGroup(
            SignUp_DetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SignUp_DetailsLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(SignUp_Details_Heading)
                .addGap(50, 50, 50)
                .addComponent(SignUp_Details_Para, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(SignUp_DetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Business_Name_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Business_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SignUp_DetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Contact_Number_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Contact_Number))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SignUp_DetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Email_Address_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Email_Address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SignUp_DetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Business_Location_Label, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(Business_Location))
                .addGap(36, 36, 36)
                .addComponent(SignUp_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        StartUp_Container.add(SignUp_Details, "signUp2");

        javax.swing.GroupLayout StartUpLayout = new javax.swing.GroupLayout(StartUp);
        StartUp.setLayout(StartUpLayout);
        StartUpLayout.setHorizontalGroup(
            StartUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StartUpLayout.createSequentialGroup()
                .addComponent(StartUp_Banner, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StartUp_Container, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        StartUpLayout.setVerticalGroup(
            StartUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(StartUp_Banner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(StartUp_Container, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        Container.add(StartUp, "start");

        SideBar.setBackground(new java.awt.Color(51, 51, 51));

        Home.setBackground(new java.awt.Color(0, 136, 255));
        Home.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/home.png"))); // NOI18N
        Home.setToolTipText("Home");
        Home.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Home.setOpaque(true);
        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HomeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HomeMousePressed(evt);
            }
        });

        Invoicing.setBackground(new java.awt.Color(255, 255, 255));
        Invoicing.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Invoicing.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/invoice.png"))); // NOI18N
        Invoicing.setToolTipText("Invoicing");
        Invoicing.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Invoicing.setOpaque(true);
        Invoicing.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InvoicingMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                InvoicingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                InvoicingMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                InvoicingMousePressed(evt);
            }
        });

        Inventory.setBackground(new java.awt.Color(255, 255, 255));
        Inventory.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Inventory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/inventory.png"))); // NOI18N
        Inventory.setToolTipText("Inventory");
        Inventory.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Inventory.setOpaque(true);
        Inventory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InventoryMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                InventoryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                InventoryMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                InventoryMousePressed(evt);
            }
        });

        Settings.setBackground(new java.awt.Color(255, 255, 255));
        Settings.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Settings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/settings.png"))); // NOI18N
        Settings.setToolTipText("Settings");
        Settings.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Settings.setOpaque(true);
        Settings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SettingsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SettingsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SettingsMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SettingsMousePressed(evt);
            }
        });

        About.setBackground(new java.awt.Color(255, 255, 255));
        About.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        About.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/about.png"))); // NOI18N
        About.setToolTipText("About");
        About.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        About.setOpaque(true);
        About.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AboutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AboutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AboutMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AboutMousePressed(evt);
            }
        });

        SignOut.setBackground(new java.awt.Color(255, 255, 255));
        SignOut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SignOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/sign-out.png"))); // NOI18N
        SignOut.setToolTipText("Sign Out");
        SignOut.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        SignOut.setOpaque(true);
        SignOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignOutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SignOutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SignOutMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SignOutMousePressed(evt);
            }
        });

        javax.swing.GroupLayout SideBarLayout = new javax.swing.GroupLayout(SideBar);
        SideBar.setLayout(SideBarLayout);
        SideBarLayout.setHorizontalGroup(
            SideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SideBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SideBarLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Inventory))
                    .addGroup(SideBarLayout.createSequentialGroup()
                        .addGroup(SideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Invoicing)
                            .addComponent(Settings)
                            .addComponent(About)
                            .addComponent(Home)
                            .addComponent(SignOut))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        SideBarLayout.setVerticalGroup(
            SideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SideBarLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(Home)
                .addGap(18, 18, 18)
                .addComponent(Invoicing)
                .addGap(18, 18, 18)
                .addComponent(Inventory)
                .addGap(18, 18, 18)
                .addComponent(Settings)
                .addGap(18, 18, 18)
                .addComponent(About)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SignOut)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout ContentLayout = new javax.swing.GroupLayout(Content);
        Content.setLayout(ContentLayout);
        ContentLayout.setHorizontalGroup(
            ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 948, Short.MAX_VALUE)
        );
        ContentLayout.setVerticalGroup(
            ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 574, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout ApplicationLayout = new javax.swing.GroupLayout(Application);
        Application.setLayout(ApplicationLayout);
        ApplicationLayout.setHorizontalGroup(
            ApplicationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ApplicationLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(SideBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        ApplicationLayout.setVerticalGroup(
            ApplicationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ApplicationLayout.createSequentialGroup()
                .addGroup(ApplicationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SideBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        Container.add(Application, "app");

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void HeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_HeaderMousePressed

    private void HeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMouseDragged
        int xx = evt.getXOnScreen();
        int yy = evt.getYOnScreen();
        this.setLocation(xx - x, yy - y);
    }//GEN-LAST:event_HeaderMouseDragged

    private void CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseClicked
        Internal.SQLite.closeDB();
        System.exit(0);
    }//GEN-LAST:event_CloseMouseClicked

    private void CloseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMousePressed
        Close.setBackground(new java.awt.Color(225, 48, 48));
    }//GEN-LAST:event_CloseMousePressed

    private void CloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseEntered
        Close.setBackground(new java.awt.Color(225, 72, 72));
    }//GEN-LAST:event_CloseMouseEntered

    private void CloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseExited
        Close.setBackground(White);
    }//GEN-LAST:event_CloseMouseExited

    private void SignIn_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignIn_ButtonActionPerformed
        String usrname = Username.getText();
        String passwd = new String(Password.getPassword());
        if (usrname.equals("") && passwd.equals(""))
            JOptionPane.showMessageDialog(null, "Please enter Username and Password they cannot be"
                + " Blank. Please Try Again!", "Credentials are Blank", JOptionPane.ERROR_MESSAGE);
        else if (Internal.SQLite.logIn(usrname, passwd)) {
            Content.removeAll();
            Speckle.Home scene = new Home();
            scene.setBounds(0, 0, 948, 574);
            Content.add(scene).setVisible(true);
            Container_Deck.show(Container, "app");
        } else
            JOptionPane.showMessageDialog(null, "The Username or Password entered are Incorrect."
                + " Please Try Again!", "Incorrect Credentials", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_SignIn_ButtonActionPerformed

    private void Next_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Next_ButtonActionPerformed
        String usrname = Internal.Security.getEncodedString(SignUp_Username.getText());
        String passwd = new String(Create_Password.getPassword());
        String confpasswd = new String(Confirm_Password.getPassword());
        if (usrname.equals("") || passwd.equals(""))
            JOptionPane.showMessageDialog(null, "Username or Password cannot be Empty. Please"
                + " Try Again!", "Username/Password Empty", JOptionPane.ERROR_MESSAGE);
        else if (!passwd.equals(confpasswd))
            JOptionPane.showMessageDialog(null, "The Passwords in Password Fields do not Match."
                + " Please Try Again!", "Password Mismatch", JOptionPane.ERROR_MESSAGE);
        else {
            Internal.SQLite.userConfig(usrname, Internal.Security.generateHash(passwd));
            StartUp_Deck.show(StartUp_Container, "signUp2");
        }
    }//GEN-LAST:event_Next_ButtonActionPerformed
     
    private void SignUp_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUp_ButtonActionPerformed
        String cname = Business_Name.getText();
        String cnum = Contact_Number.getText();
        String cmail = Email_Address.getText();
        String caddress = Business_Location.getText();
        if (cname.equals("") || cnum.equals("") || cmail.equals("") || caddress.equals(""))
            JOptionPane.showMessageDialog(null, "All Fields are Required to be Filled. Please"
                + " Try Again!", "Empty Feilds", JOptionPane.ERROR_MESSAGE);
        else {
            Internal.SQLite.compConfig(cname, cnum, cmail, caddress);
            Content.removeAll();
            Speckle.Home scene = new Home();
            scene.setBounds(0, 0, 948, 574);
            Content.add(scene).setVisible(true);
            Container_Deck.show(Container, "app");
        }
    }//GEN-LAST:event_SignUp_ButtonActionPerformed

    private void HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseClicked
        Content.removeAll();
        Speckle.Home scene = new Home();
        scene.setBounds(0, 0, 948, 574);
        Content.add(scene).setVisible(true);
    }//GEN-LAST:event_HomeMouseClicked

    private void HomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMousePressed
        Home.setBackground(Active);
        Invoicing.setBackground(White);
        Inventory.setBackground(White);
        Settings.setBackground(White);
        About.setBackground(White);
        Stored = Home.getBackground();
    }//GEN-LAST:event_HomeMousePressed

    private void HomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseEntered
        Stored = Home.getBackground();
        Home.setBackground(Hover);
    }//GEN-LAST:event_HomeMouseEntered

    private void HomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseExited
        Home.setBackground(Stored);
    }//GEN-LAST:event_HomeMouseExited

    private void InvoicingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InvoicingMouseClicked
        Content.removeAll();
        Speckle.Invoicing scene = new Invoicing();
        scene.setBounds(0, 0, 948, 574);
        Content.add(scene).setVisible(true);
    }//GEN-LAST:event_InvoicingMouseClicked

    private void InvoicingMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InvoicingMousePressed
        Home.setBackground(White);
        Invoicing.setBackground(Active);
        Inventory.setBackground(White);
        Settings.setBackground(White);
        About.setBackground(White);
        Stored = Invoicing.getBackground();
    }//GEN-LAST:event_InvoicingMousePressed

    private void InvoicingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InvoicingMouseEntered
        Stored = Invoicing.getBackground();
        Invoicing.setBackground(Hover);
    }//GEN-LAST:event_InvoicingMouseEntered

    private void InvoicingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InvoicingMouseExited
        Invoicing.setBackground(Stored);
    }//GEN-LAST:event_InvoicingMouseExited

    private void InventoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InventoryMouseClicked
        Content.removeAll();
        Speckle.Inventory scene = new Inventory();
        scene.setBounds(0, 0, 948, 574);
        Content.add(scene).setVisible(true);
    }//GEN-LAST:event_InventoryMouseClicked

    private void InventoryMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InventoryMousePressed
        Home.setBackground(White);
        Invoicing.setBackground(White);
        Inventory.setBackground(Active);
        Settings.setBackground(White);
        About.setBackground(White);
        Stored = Inventory.getBackground();
    }//GEN-LAST:event_InventoryMousePressed

    private void InventoryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InventoryMouseEntered
        Stored = Inventory.getBackground();
        Inventory.setBackground(Hover);
    }//GEN-LAST:event_InventoryMouseEntered

    private void InventoryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InventoryMouseExited
        Inventory.setBackground(Stored);
    }//GEN-LAST:event_InventoryMouseExited

    private void SettingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SettingsMouseClicked
        Content.removeAll();
        Speckle.Settings scene = new Settings();
        scene.setBounds(0, 0, 948, 574);
        Content.add(scene).setVisible(true);
    }//GEN-LAST:event_SettingsMouseClicked

    private void SettingsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SettingsMousePressed
        Home.setBackground(White);
        Invoicing.setBackground(White);
        Inventory.setBackground(White);
        Settings.setBackground(Active);
        About.setBackground(White);
        Stored = Settings.getBackground();
    }//GEN-LAST:event_SettingsMousePressed

    private void SettingsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SettingsMouseEntered
        Stored = Settings.getBackground();
        Settings.setBackground(Hover);
    }//GEN-LAST:event_SettingsMouseEntered

    private void SettingsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SettingsMouseExited
        Settings.setBackground(Stored);
    }//GEN-LAST:event_SettingsMouseExited

    private void AboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutMouseClicked
        Content.removeAll();
        Speckle.About scene = new About();
        scene.setBounds(0, 0, 948, 574);
        Content.add(scene).setVisible(true);
    }//GEN-LAST:event_AboutMouseClicked

    private void AboutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutMousePressed
        Home.setBackground(White);
        Invoicing.setBackground(White);
        Inventory.setBackground(White);
        Settings.setBackground(White);
        About.setBackground(Active);
        Stored = About.getBackground();
    }//GEN-LAST:event_AboutMousePressed

    private void AboutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutMouseEntered
        Stored = About.getBackground();
        About.setBackground(Hover);
    }//GEN-LAST:event_AboutMouseEntered

    private void AboutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutMouseExited
        About.setBackground(Stored);
    }//GEN-LAST:event_AboutMouseExited

    private void SignOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignOutMouseClicked
        Username.setText("");
        Password.setText("");
        StartUp_Deck.show(StartUp_Container, "signIn");
        Container_Deck.show(Container, "start");
        Home.setBackground(Active);
        Invoicing.setBackground(White);
        Inventory.setBackground(White);
        Settings.setBackground(White);
        About.setBackground(White);
    }//GEN-LAST:event_SignOutMouseClicked

    private void SignOutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignOutMousePressed
        SignOut.setBackground(new java.awt.Color(225, 48, 48));
    }//GEN-LAST:event_SignOutMousePressed

    private void SignOutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignOutMouseEntered
        SignOut.setBackground(new java.awt.Color(225, 56, 56));
    }//GEN-LAST:event_SignOutMouseEntered

    private void SignOutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignOutMouseExited
        SignOut.setBackground(White);
    }//GEN-LAST:event_SignOutMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the FlatIntelliJLaf look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If FlatIntelliJLaf is not available, stay with the default look and feel. */
        com.formdev.flatlaf.FlatIntelliJLaf.setup();
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("FlatIntelliJLaf".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        javax.swing.UIManager.put("ScrollBar.thumbArc", 999);
        javax.swing.UIManager.put("ScrollBar.thumbInsets", new java.awt.Insets(2, 2, 2, 2));
        javax.swing.UIManager.put("TabbedPane.showTabSeparators", true);
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Main().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel About;
    private javax.swing.JPanel Application;
    private javax.swing.JPanel Background;
    private javax.swing.JTextField Business_Location;
    private javax.swing.JLabel Business_Location_Label;
    private javax.swing.JTextField Business_Name;
    private javax.swing.JLabel Business_Name_Label;
    private javax.swing.JLabel Close;
    private javax.swing.JPasswordField Confirm_Password;
    private javax.swing.JLabel Confirm_Password_Label;
    private javax.swing.JTextField Contact_Number;
    private javax.swing.JLabel Contact_Number_Label;
    private javax.swing.JPanel Container;
    public static javax.swing.JDesktopPane Content;
    private javax.swing.JPasswordField Create_Password;
    private javax.swing.JLabel Create_Password_Label;
    private javax.swing.JTextField Email_Address;
    private javax.swing.JLabel Email_Address_Label;
    private javax.swing.JPanel Header;
    private javax.swing.JLabel Header_Logo;
    private javax.swing.JLabel Home;
    private javax.swing.JLabel Inventory;
    private javax.swing.JLabel Invoicing;
    private javax.swing.JButton Next_Button;
    private javax.swing.JPasswordField Password;
    private javax.swing.JLabel Password_Label;
    private javax.swing.JLabel Settings;
    private javax.swing.JPanel SideBar;
    private javax.swing.JPanel SignIn;
    private javax.swing.JButton SignIn_Button;
    private javax.swing.JLabel SignIn_Heading;
    private javax.swing.JLabel SignIn_Para;
    private javax.swing.JLabel SignIn_SubHeading;
    private javax.swing.JLabel SignOut;
    private javax.swing.JButton SignUp_Button;
    private javax.swing.JPanel SignUp_Details;
    private javax.swing.JLabel SignUp_Details_Heading;
    private javax.swing.JLabel SignUp_Details_Para;
    private javax.swing.JPanel SignUp_User;
    private javax.swing.JLabel SignUp_User_Heading;
    private javax.swing.JLabel SignUp_User_Para_A;
    private javax.swing.JLabel SignUp_User_Para_B;
    private javax.swing.JLabel SignUp_User_SubHeading;
    private javax.swing.JTextField SignUp_Username;
    private javax.swing.JLabel SignUp_Username_Label;
    private javax.swing.JPanel StartUp;
    private javax.swing.JLabel StartUp_Banner;
    private javax.swing.JPanel StartUp_Container;
    private javax.swing.JTextField Username;
    private javax.swing.JLabel Username_Label;
    private javax.swing.JLabel Window_Title;
    // End of variables declaration//GEN-END:variables
    private final java.awt.CardLayout Container_Deck;
    private final java.awt.CardLayout StartUp_Deck;
    private final java.awt.Color Active;
    private final java.awt.Color Hover;
    private final java.awt.Color White;
    private java.awt.Color Stored;
    private int x, y;
}
