package Speckle;

/**
 *
 * @author Astralsphere Arts
 */
public class Settings extends javax.swing.JPanel {

    /**
     * Creates new form Settings
     */
    public Settings() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Settings_Container = new javax.swing.JTabbedPane();
        User_Tab = new javax.swing.JPanel();
        User_Heading = new javax.swing.JLabel();
        User_SubHeading = new javax.swing.JLabel();
        Old_Pass_Label = new javax.swing.JLabel();
        Old_Pass = new javax.swing.JPasswordField();
        New_Pass_Label = new javax.swing.JLabel();
        New_Pass = new javax.swing.JPasswordField();
        Reset = new javax.swing.JButton();
        Details_Tab = new javax.swing.JPanel();
        Details_Heading = new javax.swing.JLabel();
        Details_SubHeading = new javax.swing.JLabel();
        Comp_Name_Label = new javax.swing.JLabel();
        Comp_Name = new javax.swing.JTextField();
        Comp_Contact_Label = new javax.swing.JLabel();
        Comp_Contact = new javax.swing.JTextField();
        Comp_Email_Label = new javax.swing.JLabel();
        Comp_Email = new javax.swing.JTextField();
        Comp_Address_Label = new javax.swing.JLabel();
        Comp_Address = new javax.swing.JTextArea();
        Save = new javax.swing.JButton();

        Settings_Container.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        Settings_Container.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        User_Heading.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        User_Heading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        User_Heading.setText("Settings");
        User_Heading.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        User_SubHeading.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        User_SubHeading.setText("Recover Credentials");

        Old_Pass_Label.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        Old_Pass_Label.setText("Old Password");

        Old_Pass.setPreferredSize(new java.awt.Dimension(64, 28));

        New_Pass_Label.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        New_Pass_Label.setText("New Password");

        New_Pass.setPreferredSize(new java.awt.Dimension(64, 28));
        New_Pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                New_PassActionPerformed(evt);
            }
        });

        Reset.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        Reset.setText("Reset");

        javax.swing.GroupLayout User_TabLayout = new javax.swing.GroupLayout(User_Tab);
        User_Tab.setLayout(User_TabLayout);
        User_TabLayout.setHorizontalGroup(
            User_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(User_TabLayout.createSequentialGroup()
                .addGroup(User_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(User_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(User_TabLayout.createSequentialGroup()
                            .addGap(305, 305, 305)
                            .addComponent(User_SubHeading))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, User_TabLayout.createSequentialGroup()
                            .addGroup(User_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, User_TabLayout.createSequentialGroup()
                                    .addGap(248, 248, 248)
                                    .addComponent(New_Pass_Label)
                                    .addGap(10, 10, 10))
                                .addGroup(User_TabLayout.createSequentialGroup()
                                    .addGap(251, 251, 251)
                                    .addComponent(Old_Pass_Label)
                                    .addGap(14, 14, 14)))
                            .addGroup(User_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Old_Pass, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(New_Pass, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(User_TabLayout.createSequentialGroup()
                        .addGap(395, 395, 395)
                        .addComponent(Reset))
                    .addGroup(User_TabLayout.createSequentialGroup()
                        .addGap(319, 319, 319)
                        .addComponent(User_Heading, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(375, Short.MAX_VALUE))
        );
        User_TabLayout.setVerticalGroup(
            User_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(User_TabLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(User_Heading, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(User_SubHeading)
                .addGap(99, 99, 99)
                .addGroup(User_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Old_Pass_Label)
                    .addComponent(Old_Pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(User_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(New_Pass_Label)
                    .addComponent(New_Pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(Reset)
                .addGap(0, 171, Short.MAX_VALUE))
        );

        Settings_Container.addTab("Login", User_Tab);

        Details_Heading.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        Details_Heading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Details_Heading.setText("Settings");
        Details_Heading.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Details_SubHeading.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        Details_SubHeading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Details_SubHeading.setText("Change Credentials");
        Details_SubHeading.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Comp_Name_Label.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        Comp_Name_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Comp_Name_Label.setText("Company Name");
        Comp_Name_Label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Comp_Name.setPreferredSize(new java.awt.Dimension(64, 28));

        Comp_Contact_Label.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        Comp_Contact_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Comp_Contact_Label.setText("Contact Number");
        Comp_Contact_Label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Comp_Contact.setPreferredSize(new java.awt.Dimension(64, 28));

        Comp_Email_Label.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        Comp_Email_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Comp_Email_Label.setText("Company Email");
        Comp_Email_Label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Comp_Address_Label.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        Comp_Address_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Comp_Address_Label.setText("Company Address");
        Comp_Address_Label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Comp_Address.setColumns(20);
        Comp_Address.setRows(5);

        Save.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        Save.setText("Save Changes");

        javax.swing.GroupLayout Details_TabLayout = new javax.swing.GroupLayout(Details_Tab);
        Details_Tab.setLayout(Details_TabLayout);
        Details_TabLayout.setHorizontalGroup(
            Details_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Details_TabLayout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addGroup(Details_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(Details_TabLayout.createSequentialGroup()
                        .addGroup(Details_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Comp_Address_Label, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(Comp_Email_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Comp_Contact_Label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(Details_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Details_TabLayout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(Comp_Address, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Details_TabLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(Details_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Comp_Contact, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Comp_Email, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Details_TabLayout.createSequentialGroup()
                        .addComponent(Comp_Name_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(Details_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Details_Heading, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Comp_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Details_SubHeading))))
                .addContainerGap(195, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Details_TabLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Save)
                .addGap(381, 381, 381))
        );
        Details_TabLayout.setVerticalGroup(
            Details_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Details_TabLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(Details_Heading, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Details_SubHeading)
                .addGap(47, 47, 47)
                .addGroup(Details_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Comp_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Comp_Name_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Details_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Comp_Contact_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Comp_Contact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Details_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Comp_Email_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Comp_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Details_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Comp_Address_Label, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                    .addComponent(Comp_Address, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(49, 49, 49)
                .addComponent(Save)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        Comp_Name_Label.getAccessibleContext().setAccessibleName("Company Name");
        Comp_Address_Label.getAccessibleContext().setAccessibleName("Company Address");

        Settings_Container.addTab("Details", Details_Tab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Settings_Container, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Settings_Container, javax.swing.GroupLayout.Alignment.TRAILING)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void New_PassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_New_PassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_New_PassActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Comp_Address;
    private javax.swing.JLabel Comp_Address_Label;
    private javax.swing.JTextField Comp_Contact;
    private javax.swing.JLabel Comp_Contact_Label;
    private javax.swing.JTextField Comp_Email;
    private javax.swing.JLabel Comp_Email_Label;
    private javax.swing.JTextField Comp_Name;
    private javax.swing.JLabel Comp_Name_Label;
    private javax.swing.JLabel Details_Heading;
    private javax.swing.JLabel Details_SubHeading;
    private javax.swing.JPanel Details_Tab;
    private javax.swing.JPasswordField New_Pass;
    private javax.swing.JLabel New_Pass_Label;
    private javax.swing.JPasswordField Old_Pass;
    private javax.swing.JLabel Old_Pass_Label;
    private javax.swing.JButton Reset;
    private javax.swing.JButton Save;
    private javax.swing.JTabbedPane Settings_Container;
    private javax.swing.JLabel User_Heading;
    private javax.swing.JLabel User_SubHeading;
    private javax.swing.JPanel User_Tab;
    // End of variables declaration//GEN-END:variables
}
